TASK_CALC = 'What is the result of the expression?'
TASK_EVEN = 'Answer "yes" if the number is even, otherwise answer "no".'
TASK_GCD = 'Find the greatest common divisor of given numbers.'
TASK_PRIME = 'Answer "yes" if given number is prime. Otherwise answer "no".'
TASK_PROGRESSION = 'What number is missing in the progression?'
